### ISSUE TITLE
switch to better API

### ISSUE THREAD

**Issue by MichaelKreil** [fredlockheed/db-fv-gtfs#3]
There is a new API from DB Station&Services ... with all trains! \o/
https://developer.deutschebahn.com/store/apis/info?name=Timetables&version=v1&provider=DBOpenData

_BTW: Thanks for your great work! I used the GTFS for: https://github.com/MichaelKreil/routing.js_

**Comment by MichaelKreil** [comment]
I'm not sure ... is the API even compatible? :/

**Comment by fredlockheed** [comment]
No, I don't think the API is compatible. I am sorry I will not have resources to rewrite the tool we're using here for this other API.
Moreover, scraping regional trains data the way long distance trains are scraped may be not feasible.
