### ISSUE TITLE
permanent filename

### ISSUE THREAD

**Issue by homtec** [fredlockheed/db-fv-gtfs#4]
Could you please provide a release with a permanent filename without dynamic URL elements like "2017"? Like "DB_gtfs_latest.zip".
Thank you for your great work.

**Comment by fredlockheed** [comment]
Should be doable.

**Comment by fredlockheed** [comment]
Here you go:

[Download](https://github.com/fredlockheed/db-fv-gtfs/releases/download/latest/db-fv-gtfs.zip)

Also prominently featured on the first page.
