### ISSUE TITLE
Data for 2018

### ISSUE THREAD

**Issue by J0ANMM** [fredlockheed/db-fv-gtfs#6]
Do you know when will the data for the year 2018 be available?

**Comment by refda** [comment]
This would be great!

**Comment by J0ANMM** [comment]
It seems the source is not yet available. When I query something like:
`https://open-api.bahn.de/bin/rest.exe/departureBoard?authKey=<myKey>&lang=de&id=008000105&date=2018-01-15&time=07%3a00&format=json`

I get:

```
{
"DepartureBoard":{
  "noNamespaceSchemaLocation":"https://open-api.bahn.de/bin/rest.exe/v1.0/xsd?name=hafasRestDepartureBoard.xsd",
  "errorCode":"SQ002",
  "errorText":"There was no journey found for the requested board or time.",
  "$":""
  }
}
```

Just for info, as an alternative the GTFS can also be found here:
https://navitia.opendatasoft.com/explore/dataset/de/table/?sort=type_file

**Comment by refda** [comment]
@J0ANMM Thanks for your hint with Navitia. I hope there will be a solution with all trains ( see https://github.com/fredlockheed/db-fv-gtfs/issues/3 ) as data source for GTFS...

**Comment by J0ANMM** [comment]
It seems that the data is available now.

The query `https://open-api.bahn.de/bin/rest.exe/departureBoard?authKey=<myKey>&lang=de&id=008000105&date=2018-03-15&time=07%3a00&format=json`

returns:

```
{
"DepartureBoard":{
  "noNamespaceSchemaLocation":"https://open-api.bahn.de/bin/rest.exe/v1.0/xsd?name=hafasRestDepartureBoard.xsd",
  "Departure":[{
    "name":"ICE 1533",
    "tyte":"ICE",
    "stopid":"8000105",
    "stop":"Frankfurt(Main)Hbf",
    "time":"07:02",
    "date":"2018-03-15",
    "direction":"Berlin Gesundbrunnen",
    "track":"10",
    "JourneyDetailRef":{
      "ref":"https://open-api.bahn.de/bin/rest.exe/v1.0/journeyDetail?ref=56..."
      }
    },{
    "name":"ICE 824",
    "type":"ICE",
    "stopid":"8000105",
    "stop":"Frankfurt(Main)Hbf",
    "time":"07:12",
    "date":"2018-03-15",
    "direction":"Essen Hbf",
    "track":"7",
    "JourneyDetailRef":{
      "ref":"https://open-api.bahn.de/bin/rest.exe/v1.0/journeyDetail?ref=81..."
      }
    },{
    "name":"IC 2273",
    "type":"IC",
    "stopid":"8000105",
    "stop":"Frankfurt(Main)Hbf",
    "time":"07:14",
    "date":"2018-03-15",
    "direction":"Karlsruhe Hbf",
    "track":"12",
    "JourneyDetailRef":{
      "ref":"https://open-api.bahn.de/bin/rest.exe/v1.0/journeyDetail?ref=11..."
      }
...
```
Is there any chance to get a release for 2018?

**Comment by fredlockheed** [comment]
@J0ANMM Navitia seems to have the same feed or the feed produced by the same tool.

**Comment by fredlockheed** [comment]
@J0ANMM @refda Year 2018 is available now:

https://github.com/fredlockheed/db-fv-gtfs/releases/tag/2018.0.0

**Comment by fredlockheed** [comment]
@refda No regional trains, sorry. DB has to publish them first, scraping regional trains is unrealistic.

**Comment by stefanw** [comment]
It looks like during the release there was a mix up. The data in the [2018.zip](https://github.com/fredlockheed/db-fv-gtfs/releases/download/latest/2018.zip) and [db-fv-gtfs.zip](https://github.com/fredlockheed/db-fv-gtfs/releases/download/latest/db-fv-gtfs.zip) release reference dates from 2015 and 2016.
